---
- name: Get undercloud version
  hosts: undercloud
  gather_facts: yes
  tags:
    - undercloud_check_version
  tasks:
    - name: Get nova-manage version
      shell: nova-manage --version
      register: nova_manage_output

    - name: Parse nova-manage version
      set_fact:
        nova_manage_version: "{% if nova_manage_output.stderr_lines[0] %}{{ nova_manage_output.stderr_lines[0].split('.')[0] }}{% else %}{{ nova_manage_output.stdout_lines[0].split('.')[0] }}{% endif %}"

    - name: Infer undercloud version
      set_fact:
        undercloud_version: "{{ (nova_manage_version|int - 4) }}"

- name: Perform overcloud update steps
  hosts: undercloud
  gather_facts: yes
  tasks:
      - name: Generate the upgrade init command env file
        template:
          src: templates/upgrade_init_command.yaml.j2
          dest: /home/stack/upgrade_init_command.yaml

      - name: Include steps for overcloud upgrade
        include: "osp{{ undercloud_version }}/steps_overcloud_upgrade.yml"
  vars:
      undercloud_rc: "~/stackrc"
      overcloud_rc: "~/overcloudrc"
      overcloud_deploy_script: "~/overcloud-deploy.sh"
      overcloud_update_script_temp: "~/overcloud-update-temp.sh"

- name: Upgrate storage nodes
  hosts: undercloud
  gather_facts: yes
  tasks:
      - name: Upgrade storage nodes
        shell: |
          source /home/stack/stackrc
          for NODE in `nova list | grep swift | awk -F "|" '{ print $2 }'` ; do upgrade-non-controller.sh --upgrade $NODE ; done

- name: Update the controller nodes
  hosts: undercloud
  gather_facts: yes
  tasks:
      - name: Start generating the update script for controllers
        copy:
          src: "~/overcloud-update-temp.sh"
          dest: "~/overcloud_update_script_controllers.sh"
          mode: 0755
          remote_src: True

      - name: Add pacemaker init script
        lineinfile:
          dest: "~/overcloud_update_script_controllers.sh"
          regexp: openstack overcloud deploy
          line: yes ""| openstack overcloud deploy -e /usr/share/openstack-tripleo-heat-templates/environments/major-upgrade-pacemaker.yaml \

      - name: run pacemaker init script
        shell: |
          exit 1
          source {{ undercloud_rc }} ;
          ~/overcloud_update_script_controllers.sh
        register: overcloud_update_controllers
        ignore_errors: True

      - name: successfull overcloud update controllers
        debug:
          msg: 'Successfully updated controller step'
        when:
          - overcloud_update_controllers.rc == 0
          - "'update finished with status COMPLETE' in overcloud_update_controllers.stdout_lines"
        ignore_errors: True

      - name: Copy script to reboot the controllers
        copy:
            src: "./files/controller_reboot.sh"
            dest: "~/controller_reboot.sh"
            mode: 0755

      - name: Execute the reboot script
        shell: |
          source {{ undercloud_rc }}
          ~/controller_reboot.sh
        register: overcloud_reboot_controllers
        ignore_errors: True

      - name: Successful reboot controllers
        debug:
          msg: 'Successfully reboot controllers step'
        when:
          - overcloud_reboot_controllers.rc == 0
        ignore_errors: True

  vars:
      undercloud_rc: "~/stackrc"
      overcloud_rc: "~/overcloudrc"
